version: '3'
services:
  app:
    build: 
      dockerfile: ./docker/node/Dockerfile
      context: ./
    tty: true
    depends_on:
      - db
    environment:
      - LOGGER_LEVEL=${LOGGER_LEVEL:-warn}
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
  db:
    build: ./docker/mysql
    ports:
      - ${DEV_DB_PORT:-3306}:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
  node_modules: