version: '3'
services:
  app:
    build: 
      dockerfile: ./docker/node/Dockerfile
      context: ./
    tty: true
    volumes:
      - ./src:/app
  db:
    build: ./docker/mysql
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
